version: "3.9"
services:
  web:
    container_name: hub
    build: ./hub
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - "mosquitto"
    volumes:
      - ./certs:/code/certs
      # openssl req -x509 -newkey rsa:4096 -nodes -out cert.pem -keyout key.pem -days 365
    ports:
      - "8000:5000"
      - "443:443"

  redis:
    container_name: redis
    image: "redis/redis-stack:latest"
    ports:
    - "6379:6379"

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - ./mosquitto:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
  
  mqtthub:
    container_name: mqtthub
    build: ./mqttdir
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - "web"