version: "3.9"
services:
  web:
    container_name: hub
    build: ./hub
    volumes:
      - ./certs:/code/certs
    ports:
      - "8000:5000"
      - "443:443"

  redis:
    image: "redis:alpine"
    container_name: redis

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - ./mosquitto:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001