version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
  redis:
    image: "redis:alpine"

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
       - ./mosquitto:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001