# syntax=docker/dockerfile:1
FROM python:3.7-alpine
WORKDIR /code
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
RUN apk add --no-cache gcc musl-dev linux-headers openssl
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . .
# run ["python", "tests.py"]
EXPOSE 5000
CMD ["gunicorn", "--certfile", "certs/cert.pem", "--keyfile", "certs/key.pem", "-b", "0.0.0.0:5000", "app:app"]
