# syntax=docker/dockerfile:1
FROM python:3.10.9-buster
WORKDIR /code
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . .
#RUN ["python", "tests.py"]
CMD ["python", "HubController.py"]