# syntax=docker/dockerfile:1
FROM python:3.7-buster
WORKDIR /code
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . .
#RUN ["python", "tests.py"]
CMD ["python", "HubController.py"]
# CMD ["gunicorn", "--certfile", "certs/cert.pem", "--keyfile", "certs/key.pem", "-b", "0.0.0.0:5000", "app:app"]
